---
galaxy_info:
  role_name: ssh
  author: Marcus DelPonte
  description: An Ansible role configuring ssh and installing public keys
  license: Apache-2.0
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      version:
        - 12
  galaxy_tags: []
